In [435]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [436]:
df = pd.read_csv('data/disease_diagnosis.csv')

In [437]:
df.head(10)

,Patient_ID,Age,Gender,Symptom_1,Symptom_2,Symptom_3,Heart_Rate_bpm,Body_Temperature_C,Blood_Pressure_mmHg,Oxygen_Saturation_%,Diagnosis,Severity,Treatment_Plan
0,1,74,Male,Fatigue,Sore throat,Fever,69,39.4,132/91,94,Flu,Moderate,Medication and rest
1,2,66,Female,Sore throat,Fatigue,Cough,95,39.0,174/98,98,Healthy,Mild,Rest and fluids
2,3,32,Male,Body ache,Sore throat,Fatigue,77,36.8,136/60,96,Healthy,Mild,Rest and fluids
3,4,21,Female,Shortness of breath,Headache,Cough,72,38.9,147/82,99,Healthy,Mild,Rest and fluids
4,5,53,Male,Runny nose,Sore throat,Fatigue,100,36.6,109/106,92,Healthy,Mild,Rest and fluids
5,6,22,Male,Sore throat,Fever,Cough,90,39.5,107/92,93,Flu,Moderate,Medication and rest
6,7,21,Male,Sore throat,Fatigue,Cough,71,37.5,126/82,93,Bronchitis,Severe,Hospitalization and medication
7,8,71,Male,Headache,Shortness of breath,Runny nose,64,38.6,153/99,99,Healthy,Mild,Rest and fluids
8,9,56,Female,Shortness of breath,Fever,Headache,103,36.2,152/71,96,Cold,Mild,Rest and fluids
9,10,53,Male,Cough,Fever,Headache,62,39.5,111/104,98,Flu,Moderate,Medication and rest

In [438]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Patient_ID           1000 non-null   int64
 1   Age                  1000 non-null   int64
 2   Gender               1000 non-null   object
 3   Symptom_1            1000 non-null   object
 4   Symptom_2            1000 non-null   object
 5   Symptom_3            1000 non-null   object
 6   Heart_Rate_bpm       1000 non-null   int64
 7   Body_Temperature_C   1000 non-null   float64
 8   Blood_Pressure_mmHg  1000 non-null   object
 9   Oxygen_Saturation_%  1000 non-null   int64
 10  Diagnosis            1000 non-null   object
 11  Severity             1000 non-null   object
 12  Treatment_Plan       1000 non-null   object
dtypes: float64(1), int64(4), object(8)
memory usage: 101.7+ KB

In [439]:
 
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Treatment_Plan'] = le.fit_transform(df['Treatment_Plan'])

print(df.head())

   Patient_ID  Age  Gender            Symptom_1    Symptom_2 Symptom_3  \
0           1   74    Male              Fatigue  Sore throat     Fever
1           2   66  Female          Sore throat      Fatigue     Cough
2           3   32    Male            Body ache  Sore throat   Fatigue
3           4   21  Female  Shortness of breath     Headache     Cough
4           5   53    Male           Runny nose  Sore throat   Fatigue

   Heart_Rate_bpm  Body_Temperature_C Blood_Pressure_mmHg  \
0              69                39.4              132/91
1              95                39.0              174/98
2              77                36.8              136/60
3              72                38.9              147/82
4             100                36.6             109/106

   Oxygen_Saturation_% Diagnosis  Severity  Treatment_Plan
0                   94       Flu  Moderate               1
1                   98   Healthy      Mild               2
2                   96   Healthy      Mild               2
3                   99   Healthy      Mild               2
4                   92   Healthy      Mild               2

In [440]:

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Severity'] = le.fit_transform(df['Severity'])

print(df.head())

   Patient_ID  Age  Gender            Symptom_1    Symptom_2 Symptom_3  \
0           1   74    Male              Fatigue  Sore throat     Fever
1           2   66  Female          Sore throat      Fatigue     Cough
2           3   32    Male            Body ache  Sore throat   Fatigue
3           4   21  Female  Shortness of breath     Headache     Cough
4           5   53    Male           Runny nose  Sore throat   Fatigue

   Heart_Rate_bpm  Body_Temperature_C Blood_Pressure_mmHg  \
0              69                39.4              132/91
1              95                39.0              174/98
2              77                36.8              136/60
3              72                38.9              147/82
4             100                36.6             109/106

   Oxygen_Saturation_% Diagnosis  Severity  Treatment_Plan
0                   94       Flu         1               1
1                   98   Healthy         0               2
2                   96   Healthy         0               2
3                   99   Healthy         0               2
4                   92   Healthy         0               2

In [441]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Diagnosis'] = le.fit_transform(df['Diagnosis'])

print(df.head())

   Patient_ID  Age  Gender            Symptom_1    Symptom_2 Symptom_3  \
0           1   74    Male              Fatigue  Sore throat     Fever
1           2   66  Female          Sore throat      Fatigue     Cough
2           3   32    Male            Body ache  Sore throat   Fatigue
3           4   21  Female  Shortness of breath     Headache     Cough
4           5   53    Male           Runny nose  Sore throat   Fatigue

   Heart_Rate_bpm  Body_Temperature_C Blood_Pressure_mmHg  \
0              69                39.4              132/91
1              95                39.0              174/98
2              77                36.8              136/60
3              72                38.9              147/82
4             100                36.6             109/106

   Oxygen_Saturation_%  Diagnosis  Severity  Treatment_Plan
0                   94          2         1               1
1                   98          3         0               2
2                   96          3         0               2
3                   99          3         0               2
4                   92          3         0               2

In [442]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Blood_Pressure_mmHg'] = le.fit_transform(df['Blood_Pressure_mmHg'])

print(df.head())

   Patient_ID  Age  Gender            Symptom_1    Symptom_2 Symptom_3  \
0           1   74    Male              Fatigue  Sore throat     Fever
1           2   66  Female          Sore throat      Fatigue     Cough
2           3   32    Male            Body ache  Sore throat   Fatigue
3           4   21  Female  Shortness of breath     Headache     Cough
4           5   53    Male           Runny nose  Sore throat   Fatigue

   Heart_Rate_bpm  Body_Temperature_C  Blood_Pressure_mmHg  \
0              69                39.4                  333
1              95                39.0                  782
2              77                36.8                  365
3              72                38.9                  488
4             100                36.6                   86

   Oxygen_Saturation_%  Diagnosis  Severity  Treatment_Plan
0                   94          2         1               1
1                   98          3         0               2
2                   96          3         0               2
3                   99          3         0               2
4                   92          3         0               2

In [443]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Symptom_2'] = le.fit_transform(df['Symptom_2'])

print(df.head())

   Patient_ID  Age  Gender            Symptom_1  Symptom_2 Symptom_3  \
0           1   74    Male              Fatigue          7     Fever
1           2   66  Female          Sore throat          2     Cough
2           3   32    Male            Body ache          7   Fatigue
3           4   21  Female  Shortness of breath          4     Cough
4           5   53    Male           Runny nose          7   Fatigue

   Heart_Rate_bpm  Body_Temperature_C  Blood_Pressure_mmHg  \
0              69                39.4                  333
1              95                39.0                  782
2              77                36.8                  365
3              72                38.9                  488
4             100                36.6                   86

   Oxygen_Saturation_%  Diagnosis  Severity  Treatment_Plan
0                   94          2         1               1
1                   98          3         0               2
2                   96          3         0               2
3                   99          3         0               2
4                   92          3         0               2

In [444]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Symptom_1'] = le.fit_transform(df['Symptom_1'])

print(df.head())

   Patient_ID  Age  Gender  Symptom_1  Symptom_2 Symptom_3  Heart_Rate_bpm  \
0           1   74    Male          2          7     Fever              69
1           2   66  Female          7          2     Cough              95
2           3   32    Male          0          7   Fatigue              77
3           4   21  Female          6          4     Cough              72
4           5   53    Male          5          7   Fatigue             100

   Body_Temperature_C  Blood_Pressure_mmHg  Oxygen_Saturation_%  Diagnosis  \
0                39.4                  333                   94          2
1                39.0                  782                   98          3
2                36.8                  365                   96          3
3                38.9                  488                   99          3
4                36.6                   86                   92          3

   Severity  Treatment_Plan
0         1               1
1         0               2
2         0               2
3         0               2
4         0               2

In [445]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Gender'] = le.fit_transform(df['Gender'])

print(df.head())

   Patient_ID  Age  Gender  Symptom_1  Symptom_2 Symptom_3  Heart_Rate_bpm  \
0           1   74       1          2          7     Fever              69
1           2   66       0          7          2     Cough              95
2           3   32       1          0          7   Fatigue              77
3           4   21       0          6          4     Cough              72
4           5   53       1          5          7   Fatigue             100

   Body_Temperature_C  Blood_Pressure_mmHg  Oxygen_Saturation_%  Diagnosis  \
0                39.4                  333                   94          2
1                39.0                  782                   98          3
2                36.8                  365                   96          3
3                38.9                  488                   99          3
4                36.6                   86                   92          3

   Severity  Treatment_Plan
0         1               1
1         0               2
2         0               2
3         0               2
4         0               2

In [446]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Symptom_3'] = le.fit_transform(df['Symptom_3'])

print(df.head())

   Patient_ID  Age  Gender  Symptom_1  Symptom_2  Symptom_3  Heart_Rate_bpm  \
0           1   74       1          2          7          3              69
1           2   66       0          7          2          1              95
2           3   32       1          0          7          2              77
3           4   21       0          6          4          1              72
4           5   53       1          5          7          2             100

   Body_Temperature_C  Blood_Pressure_mmHg  Oxygen_Saturation_%  Diagnosis  \
0                39.4                  333                   94          2
1                39.0                  782                   98          3
2                36.8                  365                   96          3
3                38.9                  488                   99          3
4                36.6                   86                   92          3

   Severity  Treatment_Plan
0         1               1
1         0               2
2         0               2
3         0               2
4         0               2

In [447]:
df.head()

,Patient_ID,Age,Gender,Symptom_1,Symptom_2,Symptom_3,Heart_Rate_bpm,Body_Temperature_C,Blood_Pressure_mmHg,Oxygen_Saturation_%,Diagnosis,Severity,Treatment_Plan
0,1,74,1,2,7,3,69,39.4,333,94,2,1,1
1,2,66,0,7,2,1,95,39.0,782,98,3,0,2
2,3,32,1,0,7,2,77,36.8,365,96,3,0,2
3,4,21,0,6,4,1,72,38.9,488,99,3,0,2
4,5,53,1,5,7,2,100,36.6,86,92,3,0,2

In [448]:
cv = df.to_csv("knn1.csv")

In [449]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Gender'] = le.fit_transform(df['Gender'])

print(df.head(1000))

     Patient_ID  Age  Gender  Symptom_1  Symptom_2  Symptom_3  Heart_Rate_bpm  \
0             1   74       1          2          7          3              69
1             2   66       0          7          2          1              95
2             3   32       1          0          7          2              77
3             4   21       0          6          4          1              72
4             5   53       1          5          7          2             100
..          ...  ...     ...        ...        ...        ...             ...
995         996   58       0          5          7          2             113
996         997   52       1          1          6          3              79
997         998   23       1          0          4          5              66
998         999   76       0          4          7          0              93
999        1000   62       1          1          2          0              83

     Body_Temperature_C  Blood_Pressure_mmHg  Oxygen_Saturation_%  Diagnosis  \
0                  39.4                  333                   94          2
1                  39.0                  782                   98          3
2                  36.8                  365                   96          3
3                  38.9                  488                   99          3
4                  36.6                   86                   92          3
..                  ...                  ...                  ...        ...
995                39.8                  706                   98          3
996                37.5                  657                   90          0
997                37.4                  860                   92          3
998                39.1                  614                   98          3
999                39.4                  228                   92          0

     Severity  Treatment_Plan
0           1               1
1           0               2
2           0               2
3           0               2
4           0               2
..        ...             ...
995         0               2
996         2               0
997         0               2
998         0               2
999         2               0

[1000 rows x 13 columns]

In [450]:
df.dropna(how='any',inplace=True)

In [451]:
len(df)

1000

In [452]:
df.columns

Index(['Patient_ID', 'Age', 'Gender', 'Symptom_1', 'Symptom_2', 'Symptom_3',
       'Heart_Rate_bpm', 'Body_Temperature_C', 'Blood_Pressure_mmHg',
       'Oxygen_Saturation_%', 'Diagnosis', 'Severity', 'Treatment_Plan'],
      dtype='object')

In [453]:
df.Symptom_3.value_counts()

Symptom_3
4    145
6    130
0    129
1    125
5    124
3    120
2    118
7    109
Name: count, dtype: int64

In [454]:
df.Symptom_3.value_counts()

Symptom_3
4    145
6    130
0    129
1    125
5    124
3    120
2    118
7    109
Name: count, dtype: int64

In [455]:
xx = df.drop(['Symptom_3'], axis=1)

In [456]:
yy = df.Symptom_3.values

In [457]:
from sklearn.model_selection import train_test_split

xx_train, xx_test, yy_train, yy_test = train_test_split(xx,yy,test_size=0.25)

In [458]:
len(xx_train)

750

In [459]:
len(xx_test)

250

In [460]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
sc.fit(xx_train)
xx_train_sc = sc.transform(xx_train)
xx_test_sc = sc.transform(xx_test)

In [461]:
xx_train_sc

array([[ 1.5824632 , -0.12002298, -0.98412598, ...,  0.63435913,
        -0.62892799,  0.62892799],
       [ 0.9701316 , -0.00454224, -0.98412598, ..., -1.08632567,
        -0.62892799,  0.62892799],
       [-1.38578829,  1.38122664, -0.98412598, ...,  0.63435913,
        -0.62892799,  0.62892799],
       ...,
       [-1.51033031,  1.66992849, -0.98412598, ..., -1.94666806,
         1.92078008, -1.92078008],
       [-1.29238177, -1.04386891,  1.01613007, ..., -1.08632567,
        -0.62892799,  0.62892799],
       [ 0.3820165 , -1.56353224, -0.98412598, ...,  0.63435913,
        -0.62892799,  0.62892799]], shape=(750, 12))

In [462]:
xx_test_sc

array([[ 1.24343215, -0.98612854, -0.98412598, ...,  0.63435913,
        -0.62892799,  0.62892799],
       [-1.43076179,  0.74608257, -0.98412598, ...,  0.63435913,
        -0.62892799,  0.62892799],
       [ 1.65511271,  0.1109385 , -0.98412598, ...,  0.63435913,
        -0.62892799,  0.62892799],
       ...,
       [ 0.25747448,  0.57286146, -0.98412598, ..., -1.94666806,
         1.92078008, -1.92078008],
       [-0.08501607,  0.16867887, -0.98412598, ...,  0.63435913,
        -0.62892799,  0.62892799],
       [-1.16783975, -0.40872483, -0.98412598, ...,  0.63435913,
        -0.62892799,  0.62892799]], shape=(250, 12))

In [463]:
from sklearn.neighbors import KNeighborsClassifier

model_knn = KNeighborsClassifier(n_neighbors=7)

model_knn.fit(xx_train_sc, yy_train)

KNeighborsClassifier(n_neighbors=7)

In [464]:
yy_pred_knn = model_knn.predict(xx_test_sc)

In [465]:
yy_pred_knn

array([6, 3, 1, 1, 3, 2, 2, 6, 3, 3, 3, 3, 3, 6, 1, 4, 0, 2, 5, 6, 5, 5,
       5, 6, 1, 5, 2, 3, 4, 7, 7, 0, 1, 2, 7, 4, 0, 4, 0, 1, 7, 6, 7, 0,
       2, 5, 5, 1, 1, 6, 2, 0, 7, 5, 0, 3, 3, 2, 5, 6, 7, 2, 7, 0, 0, 0,
       1, 2, 1, 1, 4, 4, 1, 2, 2, 0, 0, 7, 2, 6, 6, 6, 0, 1, 4, 2, 1, 4,
       4, 1, 1, 4, 1, 0, 4, 3, 1, 1, 6, 0, 1, 7, 4, 1, 3, 0, 7, 1, 4, 4,
       6, 0, 4, 6, 1, 6, 0, 0, 4, 6, 0, 3, 0, 2, 7, 7, 4, 3, 0, 4, 2, 5,
       3, 1, 6, 1, 3, 0, 0, 5, 0, 4, 4, 2, 2, 1, 0, 1, 2, 4, 0, 0, 1, 6,
       0, 0, 2, 3, 5, 5, 7, 1, 4, 0, 2, 3, 1, 3, 6, 6, 4, 3, 1, 2, 3, 3,
       3, 7, 1, 2, 5, 4, 5, 4, 0, 1, 6, 1, 0, 0, 1, 4, 2, 5, 2, 4, 5, 3,
       0, 2, 2, 6, 6, 3, 3, 6, 3, 4, 6, 1, 2, 0, 5, 0, 7, 0, 1, 1, 3, 4,
       4, 4, 5, 7, 4, 4, 3, 4, 0, 5, 0, 3, 2, 0, 3, 7, 0, 0, 0, 4, 0, 6,
       7, 3, 1, 1, 1, 7, 0, 0])

In [466]:
yy_test

array([6, 5, 2, 5, 3, 0, 4, 6, 6, 6, 1, 0, 2, 4, 2, 6, 0, 3, 2, 6, 7, 5,
       4, 7, 3, 4, 2, 4, 7, 2, 0, 7, 1, 0, 5, 6, 1, 4, 1, 1, 5, 0, 3, 7,
       1, 3, 5, 6, 2, 7, 6, 0, 5, 3, 4, 3, 7, 2, 0, 6, 0, 1, 4, 3, 0, 5,
       3, 4, 6, 7, 7, 5, 3, 4, 2, 1, 5, 4, 2, 3, 4, 6, 2, 0, 2, 2, 7, 1,
       5, 1, 3, 0, 3, 1, 7, 3, 7, 4, 6, 7, 2, 1, 3, 1, 5, 2, 6, 3, 3, 3,
       6, 0, 4, 6, 5, 4, 5, 0, 1, 4, 1, 4, 7, 7, 3, 0, 0, 1, 7, 1, 1, 2,
       3, 4, 5, 0, 4, 6, 1, 3, 0, 4, 2, 4, 3, 6, 6, 1, 0, 2, 2, 4, 2, 1,
       4, 3, 0, 0, 6, 3, 1, 1, 0, 6, 6, 3, 5, 1, 6, 3, 0, 1, 6, 2, 1, 7,
       3, 5, 1, 0, 2, 5, 5, 3, 0, 3, 2, 1, 6, 7, 1, 3, 0, 5, 3, 7, 2, 2,
       5, 3, 7, 6, 1, 4, 7, 4, 3, 0, 2, 1, 6, 1, 7, 7, 0, 7, 3, 1, 3, 7,
       6, 5, 0, 1, 3, 7, 2, 5, 7, 7, 6, 7, 2, 6, 6, 7, 4, 1, 1, 5, 4, 7,
       5, 6, 7, 1, 1, 1, 2, 6])

In [467]:
from sklearn.metrics import accuracy_score

print(round(accuracy_score(yy_test,yy_pred_knn)*100,2))

21.2